// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmosslpnicsilbrbimpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtb3NzbHBuaWNzaWxicmJpbXByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NjAwODIsImV4cCI6MjA3MDEzNjA4Mn0.1InxMmsdmz4jSGu0M3NZkviatLAf8O4ReyykDTRDTh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});